version: 2

jobs:
  prepare:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: .
          command: |
            docker system prune -f --volumes
            ./env-prepare

  wagtail-cms:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build chembience wagtail cms
          working_directory: .
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures
            docker-compose -f docker-compose.build.yml build
            docker-compose -f docker-compose.build.yml push


workflows:
  version: 2
  wagtail-cms:
    jobs:
      - prepare
      - wagtail-cms:
          requires:
            - prepare




